config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Define routes for venues
  get "profile", to: "pages#profile"
  get "search", to: "pages#search"
  
  resources :venues do
    resources :bookings, only: [:new, :create, :edit]
  end

  resources :bookings, only: [ :destroy, :update ]


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :venue
  
  validates :date, :hours, presence: true
  validates :hours, numericality: { less_than_or_equal_to: 24 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :venues
  has_many :bookings
  has_many :received_bookings, through: :venues, source: :bookings

end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  has_many :bookings


  # validates :name, :address, :city, :country, :price, presence: true
  # validates :price, numericality: { greater_than_or_equal_to: 0 }

  #geocoded_by :address
  #after_validation :geocode, if: :will_save_change_to_address?


  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :description, presence: true, length: { minimum: 50 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }


  include PgSearch::Model
  pg_search_scope :search_by_city,
  against: [ :address ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

    def new
        @booking = Booking.new
    end

    def create
        @venue = Venue.find(params[:venue_id])
        @booking = Booking.new(bookings_params)
        @booking.venue = @venue
        @booking.user = current_user
         
        if @booking.save
            redirect_to profile_path
        else
            render "venues/show", status: :unprocessable_entity
        end
        
    end

    def destroy
        @booking = Booking.find(params[:id])
        @booking.destroy
        redirect_to profile_path(current_user)

    end

    private

    def bookings_params
        params.require(:booking).permit(:venue_id, :date, :hours, :total)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :search ]

  def profile
    
    # @venues = Venue.all
    @venues = Venue.where(user_id: current_user.id)

    @bookings = Booking.where(user_id: current_user.id)

    # @other_bookings = Booking.where(venue_id: @venue.id)
  end

  def home
    @venues = Venue.all.limit(8)
  end

  def search
    @venues = Venue.search_by_city(params[:query])
  end
  
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show edit]

  # GET /venues
  def index
    @venues = Venue.all
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/:id
  def show
    @venue = Venue.find(params[:id])
    @marker = [{ lat: @venue.latitude, lng: @venue.longitude }]
    
    @booking = Booking.new
    @bookings = Booking.where(venue_id: @venue.id)

  end

  # POST /venues
  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user
    # if save is successful, user is redirected venue’s show page with a success message.
    if @venue.save
      redirect_to @venue, notice: 'Venue was successfully created!'
    # if save fails (due to validation errors), form is re-rendered, and user remains on new page,
    # with an appropriate status code (422 Unprocessable Entity).
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def update
    @venue = Venue.find(params[:id])
    @venue.update(venue_params)
    redirect_to venue_path(@venue)
  end

  # DELETE /venues/:id
  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy
    redirect_to profile_path, status: :see_other
  end


  private

  def venue_params
    params.require(:venue).permit(:name, :address, :description, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StayEventful</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>


  <%# <% flash.each do |key, value| %>
      <%# <div class="flash <%= key"<%= value %>
    <%# <% end %>
    


  <div>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
    <h2 class="mb-4">A place to party like is not your home!</h2>
    <p> <%= link_to "Find a Venue", venues_path %> </p>
</div>

<div class="after-banner">
    <h2>Party Venues for Hire</h2>
    <p>Dreaming of hosting a private party in a home that is not your own?</p>
    <p>Stay Eventful has the best private party venues for hire. Find your perfect party venue today.</p>

</div>

app/views/pages/profile.html.erb
<div class="container">

    <h3 class="mt-4" style="font-weight: bold; font-size: 40px; padding-top: 30px;">DASHBOARD</h3>
    <P style="padding-bottom: 10px;"><em><%= current_user.email %> </em></P>

    <div class="profile row my-4">

        <div class="row-container" style="margin-top: 60px;">
        <h3 style="margin-bottom: 40px;">Manage My Venues</h3>
        <table class="table table-bordered table-hover table-responsive">
            <thead class="thead-dark">
                <tr class="table-active">
                    <!-- <th></th> -->
                    <th>Venue Name</th>
                    <th>Location</th>
                    <th>Price per hour</th>
                    <th> # </th>
                  </tr>
                </thead>

        <% @venues.each do |venue| %>
    
              <tr>
                <!-- <td class="bg-white"><% if venue.photo.attached? %>
                    <%= cl_image_tag venue.photo.key %>
                  <% else %>
                    <img src="<%= venue.image_url %>">
                  <% end %></td> -->
                <td class="bg-white"> <%= venue.name %>  </th>
                <td class="bg-white">   <%= venue.address %> </td>
                <td class="bg-white"> €<%= venue.price.to_i %> </td>
                <td class="bg-white"> <%= link_to "View", venue_path(venue) %> </td>
                </tr>
        <% end %>
    </table>
    </div>

    <div class="row">
        <div class="row-container" style="margin-top: 60px;">
            <h3 style="margin-bottom: 40px;">Bookings On My Venues</h3>
            <table class="table table-bordered table-hover table-responsive">
                <thead class="thead-dark">
                    <tr class="table-active">
                        <!-- <th></th> -->
                        <th>Venue Name</th>
                        <th>Booked By</th>
                        <th>Booked On</th>
                        <th>Number of Hours</th>
                        <th> Total </th>
                        <th> # </th>
                      </tr>
                    </thead>
    
                    <% current_user.received_bookings.each do |b|%>
                    <% booking_creater = User.find(b.user_id) %>
        
                  <tr>
                    <td class="bg-white"> <%= b.venue.name %>  </td>
                    <td class="bg-white"> <%= booking_creater.email %> </td>
                    <td class="bg-white"> <%= b.date %> </td>
                    <td class="bg-white"> <%= b.hours %> </td>
                    <td class="bg-white"> €<%= b.venue.price.to_i * b.hours  %> </td>
                    <td class="bg-white"> <%= link_to "Delete", booking_path(b), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %> </td>
                    </tr>
            <% end %>
        </table>
        </div>
    </div>

    <div class="row">
        <div class="row-container" style="margin-top: 60px;">
            <h3 style="margin-bottom: 40px;">Manage My Bookings</h3>
            <table class="table table-bordered table-hover table-responsive">
                <thead class="thead-dark">
                    <tr class="table-active">
                        <!-- <th></th> -->
                        <th>Venue Name</th>
                        <th>Booked For</th>
                        <th>Number of Hours</th>
                        <th> Total </th>
                        <th> # </th>
                      </tr>
                    </thead>
    
                    <% current_user.bookings.each do |booking| %>
                    
        
                  <tr>
                    <td class="bg-white"> <%= booking.venue.name %>  </td>
                    <td class="bg-white"> <%= booking.date %> </td>
                    <td class="bg-white"> <%= booking.hours %> </td>
                    <td class="bg-white"> €<%= booking.venue.price.to_i * booking.hours  %> </td>
                    <td class="bg-white"> <%= link_to "Delete", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %> </td>
                    </tr>
            <% end %>
        </table>
        </div>
    </div>
    
<!--     
    <div class="col-6 p-4">
        
        <div class="row-container">
            <h3 style="margin-bottom: 40px;">Manage Venues</h3>
            <% @venues.each do |venue| %>
            <div class="card-product mb-4">
                <% if venue.photo.attached? %>
                      <%= cl_image_tag venue.photo.key %>
                    <% else %>
                      <img src="<%= venue.image_url %>">
                    <% end %>
                <div class="card-product-infos">
                <h2><%= venue.name %></h2> 
                <div class="location-with-icon">
                    <i class="fa-solid fa-location-dot pb-2" style="color: #fe019a;"></i>
                    <div class ="pt-1"><p> <%= venue.address %> </p> </div>
                </div>
                 <p> <%= venue.description %></p> 
                
                <!-- <div class=" my-2">
                    <%= link_to "View", venue_path(venue) %>
                    <%= link_to "Delete",
                    venue_path(venue),
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                </div>
                </div>
            </div>
            <% end %>
        </div>
    </div> --> 

 


</div>
</div>

app/views/pages/search.html.erb
<div class="container">

    <div class="search-bar row justify-content-center">
      <div class="col-sm-8 my-3">
        <%= form_with url: search_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "type a city"
            %>
          <%= submit_tag "Search", name: "", class: "btn btn-warning" %>
        <% end %>
        <p style="color: rgba(0, 0, 0, 0.477); padding-top: 5px;"><em>Results...</em></p>
      </div>
    </div>
  
      <div class="card-container my-3">
          <% @venues.each do |venue| %>
              <div class="flex-card mb-3">
                  <div> <a href=<%= venue_path(venue) %>>
                      <% if venue.photo.attached? %>
                        <%= cl_image_tag venue.photo.key %>
                      <% else %>
                        <img src="<%= venue.image_url %>">
                      <% end %>
                    </a>
                    </div>
                  <div class="p-3">
                      <a href=<%= venue_path(venue) %>> <h2> <%= venue.name %> </h2></a>
                      <p class="mb-0"> <%= venue.address %> </p>
                      <p> <strong> € <%= venue.price.to_i %> </strong> </p>
                  </div>
              </div>
          <% end %>
  
  
  
      </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="copyright">
    <i class="fa-regular fa-copyright"></i>
   Copyright 2024 by StayEventful
  </div>

  <div class="about">
  About
  Contact
  </div>

  <div class="icons">
    <ul>

      <li><i class="fa-brands fa-facebook"></i></li>
      <li><i class="fa-brands fa-instagram"></i></li>
      <li><i class="fa-brands fa-x-twitter"></i></li>
      <li><i class="fa-brands fa-youtube"></i></li>

    </ul>
   </div>
 </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h3>StayEventful</h3>
    <% end %>

    <!-- <form class="example">
    <input type="text" placeholder="Search..." name="search" button type="submit">
    <button type="submit"><i class="fa fa-search"></i></button>
    </form> -->

    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> %>
      <%# <span class="navbar-toggler-icon"></span> %>
    <%# </button> %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Find a Venue", venues_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "List Your Venue", new_venue_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">

          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/arthur-littm", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Find a Venue", venues_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "List Your Venue", new_venue_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/venues/edit.html.erb
<div class="container form-container">
  <h1 class="form-heading">Polish Your Party Place!  ✨</h1>
  <%= simple_form_for @venue do |f| %>

    <% if @venue.errors.any? %>
      <div id="error_explanation" class="error-message">
        <p>Oops! Something went wrong!</p>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.input :name, input_html: {class: "rounded-input"}, placeholder: "Enter the name of the venue" %>

      <%= f.input :address,
          input_html: {data: {address_autocomplete_target: "address"}, class: "d-none", placeholder: "Enter the address"},
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}, class: "address_input"}
        %>
    </div>

    <div class="form-group">
      <%= f.input :description, as: :text, input_html: {rows: 5, class: "rounded-textarea"}, placeholder: "Describe the venue" %>
      <%= f.input :price, input_html: {class: "rounded-input"}, placeholder: "Enter the price per hour" %>
    </div>

    <div class="form-group">
      <%= f.input :photo, as: :file, label: "Upload Image", input_html: {class: "form-control-file"} %>
    </div>

    <%= f.button :submit, "Edit Venue", class: "btn btn-success" %>
  <% end %>
</div>

app/views/venues/index.html.erb
<div class="container">

  <div class="search-bar row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: search_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "type a city"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-warning" %>
      <% end %>
    </div>
  </div>

    <div class="card-container my-3">
        <% @venues.each do |venue| %>
            <div class="flex-card mb-3">
                <div> <a href=<%= venue_path(venue) %>>
                    <% if venue.photo.attached? %>
                      <%= cl_image_tag venue.photo.key %>
                    <% else %>
                      <img src="<%= venue.image_url %>">
                    <% end %>
                  </a>
                  </div>
                <div class="p-3">
                    <a href=<%= venue_path(venue) %>> <h2> <%= venue.name %> </h2></a>
                    <p class="mb-0"> <%= venue.address %> </p>
                    <p> <strong> € <%= venue.price.to_i %> </strong> </p>
                </div>
            </div>
        <% end %>



    </div>
</div>

app/views/venues/new.html.erb
<div class="container form-container">
  <h1 class="form-heading">Showcase Your Epic Venue Here!  🎉</h1>
  <%= simple_form_for @venue do |f| %>

    <% if @venue.errors.any? %>
      <div id="error_explanation" class="error-message">
        <p>Oops! Something went wrong!</p>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.input :name, input_html: {class: "rounded-input"}, placeholder: "Enter the name of the venue" %>

      <%= f.input :address,
          input_html: {data: {address_autocomplete_target: "address"}, placeholder: "Enter the address"},
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}, class: "address_input"}
        %>
    </div>

    <div class="form-group">
      <%= f.input :description, as: :text, input_html: {rows: 5, class: "rounded-textarea"}, placeholder: "Describe the venue" %>
      <%= f.input :price, input_html: {class: "rounded-input"}, placeholder: "Enter the price per hour" %>
    </div>

    <div class="form-group">
      <%= f.input :photo, as: :file, label: "Upload Image", input_html: {class: "form-control-file"} %>
    </div>

    <%= f.button :submit, "Create Venue", class: "btn btn-success" %>
  <% end %>
</div>

app/views/venues/show.html.erb
<div class="container">

  <div class="show my-4">
    <% if @venue.photo.attached? %>
      <div> <%= cl_image_tag @venue.photo.key %> </div>
    <% else %>
      <div> <img src=<%= @venue.image_url %> > </div>
    <% end %>
  </div>


  <div class="venue-bookings-container row mb-4 justify-content-between">

    <div class="col-6">

      <h2 class="mt-4"> <%= @venue.name %> </h2>
      <p style="font-size: 18px;"> <strong>Price per Hour:</strong> €<%= @venue.price.to_i %></p>
      <div class="location-with-icon">
        <i class="fa-solid fa-location-dot fa-lg" style="color: #fe019a;"></i>
        <div class ="txt"><p> <%= @venue.address %> </p> </div>
      </div>
      <p> <%= @venue.description %> </p>

      <% if user_signed_in? %>
          <% if @venue.user_id == current_user.id %>
            <div class="yellow-btn my-4">
              <%= link_to "Edit", edit_venue_path(@venue) %>
              <%= link_to "Delete", venue_path(@venue), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            </div>
          <% end %>

    </div>


    <div class="col-4 px-2">

      <% if current_user.id == @venue.user_id %>
        <!-- <h2  class="mt-4" style="font-size: 24px;"> See bookings on this venue: </h2> -->

        <% if @bookings.exists? %>

          <% @bookings.each do |b|%>
           <% booking_creater = User.find(b.user_id) %>
            <!-- <div class="notification">
              <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="avatar-large" >
              <div class="notification-content">
                <p><small> <strong>Booking Date: </strong><%= b.date %> </small></p>
                <p><small> <strong>Booked By:  </strong><%= booking_creater.email  %> </small></p>
                <p><small> <strong>Number of Hours: </strong><%= b.hours  %> </small></p>
                <p> <small> <strong>Total: </strong>€<%= b.hours * @venue.price.to_i %> </small></p> -->
              </div>

              <div class="notification-actions">
              <!-- <a href="#">Edit <i class="fas fa-pencil-alt"></i></a> -->
                <!-- <a href="#">Delete <i class="far fa-trash-alt"></i></a> -->
              </div>
            </div>
          <% end %>

        <% else %>
          <!-- <p style="color: #000000a9;"><em>This venue has no bookings to display.</em></p> -->
        <% end %>


      <% else %>

        <div class="form-container">
          <%= simple_form_for [@venue, @booking] do |f| %>
            <% if @booking.errors.any? %>
              <div id="error_explanation" class="error-message">
                <p>Oops! Something went wrong!</p>
              </div>
            <% end %>

            <div class="form-group">
              <%= f.input :date, input_html: {class: "rounded-input"}, lable: "Pick a Date" %>
              <%= f.input :hours, input_html: {class: "rounded-input"}, placeholder: "For how many hours?" %>
            </div>

            <%= f.button :submit, "Create Booking", class: "btn btn-success" %>
          <% end %>
        </div>

      <% end %>

      <% else %>
      <div class="sign-up-to-party">
        <p style="padding-top: 50px; color: rgba(0, 0, 0, 0.507);"><em> Want to host a party here? <strong>Create an account</strong> to book this venue.</em></p>
      </div>
        <% end %>
    </div>
  </div>


  <div class="map-box-container mb-4">
    <div style="width: 100%; height: 400px; border-radius: 15px;"
      data-controller="map"
      data-map-markers-value="<%= @marker.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

</div>